-- ═══════════════════════════════════════════════════════════════
--  Therapy Library Seed Data
--  Run AFTER the migration creates the tables
-- ═══════════════════════════════════════════════════════════════

-- PEPTIDES
INSERT INTO therapies (slug, name, therapy_type, category, short_description, mechanism_plain_english, common_uses, potential_benefits, potential_risks, administration_routes, evidence_rating, prescription_required, fda_status) VALUES
('bpc-157', 'BPC-157', 'peptide', 'recovery', 'Body Protection Compound — a peptide studied for tissue repair and gut healing.', 'Derived from a protein found in gastric juice. May support blood vessel formation and tissue repair signaling.', ARRAY['Tendon/ligament support','Gut healing','Joint recovery'], ARRAY['May accelerate tissue repair','May support gut lining integrity','May reduce inflammation locally'], ARRAY['Limited human trial data','Injection site reactions','Not FDA-approved for any condition'], ARRAY['Subcutaneous injection','Oral'], 'C', true, 'Not FDA-approved'),
('tb-500', 'TB-500 (Thymosin Beta-4)', 'peptide', 'recovery', 'Peptide studied for wound healing, tissue repair, and flexibility.', 'Naturally occurring peptide involved in cell migration and tissue repair. May support recovery from soft tissue injuries.', ARRAY['Muscle recovery','Wound healing','Flexibility support'], ARRAY['May support tissue regeneration','May improve flexibility','May reduce recovery time'], ARRAY['Limited human data','Not FDA-approved','Injection site reactions'], ARRAY['Subcutaneous injection'], 'C', true, 'Not FDA-approved'),
('kpv', 'KPV', 'peptide', 'inflammation', 'Anti-inflammatory peptide fragment derived from alpha-MSH.', 'A fragment of alpha-melanocyte stimulating hormone with targeted anti-inflammatory properties, particularly studied for gut inflammation.', ARRAY['Gut inflammation','Inflammatory conditions','Immune modulation'], ARRAY['May reduce gut inflammation','May support immune balance','May help with inflammatory skin conditions'], ARRAY['Very limited human data','Not FDA-approved','Research still early'], ARRAY['Oral','Subcutaneous injection','Topical'], 'D', true, 'Not FDA-approved'),
('cjc-1295', 'CJC-1295', 'peptide', 'longevity', 'Growth hormone releasing hormone analog studied for GH optimization.', 'Stimulates the pituitary gland to release growth hormone in a pulsatile pattern, mimicking natural GH release.', ARRAY['Growth hormone optimization','Body composition','Recovery'], ARRAY['May support lean body mass','May improve sleep quality','May support recovery'], ARRAY['Water retention','Joint discomfort','Altered glucose metabolism','Not FDA-approved'], ARRAY['Subcutaneous injection'], 'C', true, 'Not FDA-approved'),
('ipamorelin', 'Ipamorelin', 'peptide', 'longevity', 'Selective growth hormone secretagogue with a favorable safety profile.', 'Stimulates GH release without significantly affecting cortisol or prolactin, making it one of the more selective GH peptides.', ARRAY['Growth hormone optimization','Recovery','Sleep quality'], ARRAY['May support GH levels','May improve sleep','Relatively selective action'], ARRAY['Headache','Water retention','Not FDA-approved'], ARRAY['Subcutaneous injection'], 'C', true, 'Not FDA-approved'),
('tesamorelin', 'Tesamorelin', 'peptide', 'metabolic', 'FDA-approved GHRH analog for reducing visceral fat in specific populations.', 'Stimulates growth hormone release. FDA-approved to reduce excess abdominal fat in HIV-associated lipodystrophy.', ARRAY['Visceral fat reduction','Body composition','Metabolic health'], ARRAY['Reduces visceral adipose tissue','FDA-approved for specific indication','Well-studied safety profile'], ARRAY['Injection site reactions','Joint pain','Peripheral edema','Glucose changes'], ARRAY['Subcutaneous injection'], 'A', true, 'FDA-approved (HIV lipodystrophy)'),
('aod-9604', 'AOD-9604', 'peptide', 'metabolic', 'Fragment of human growth hormone studied for fat metabolism.', 'A modified fragment of HGH (amino acids 176-191) that may stimulate fat breakdown without the growth-promoting effects of full HGH.', ARRAY['Fat metabolism','Body composition','Weight management support'], ARRAY['May support fat metabolism','Does not affect blood sugar like full HGH','Targeted action'], ARRAY['Limited human efficacy data','Not FDA-approved','GI discomfort reported'], ARRAY['Subcutaneous injection','Oral'], 'C', true, 'Not FDA-approved'),
('mots-c', 'MOTS-c', 'peptide', 'longevity', 'Mitochondrial-derived peptide studied for metabolic and exercise performance.', 'Encoded within mitochondrial DNA. May regulate metabolic homeostasis and improve cellular energy production.', ARRAY['Metabolic health','Exercise performance','Cellular energy'], ARRAY['May improve insulin sensitivity','May enhance exercise capacity','May support mitochondrial function'], ARRAY['Very limited human data','Not FDA-approved','Research primarily preclinical'], ARRAY['Subcutaneous injection'], 'D', true, 'Not FDA-approved'),
('ss-31', 'SS-31 (Elamipretide)', 'peptide', 'longevity', 'Mitochondria-targeted peptide in clinical trials for mitochondrial conditions.', 'Penetrates and concentrates in the inner mitochondrial membrane, potentially stabilizing energy production.', ARRAY['Mitochondrial support','Cellular energy','Age-related conditions'], ARRAY['Targeted mitochondrial action','In active clinical trials','May support cellular energy'], ARRAY['In clinical development','Not yet approved','Limited access'], ARRAY['Subcutaneous injection'], 'C', true, 'Investigational'),
('epitalon', 'Epitalon', 'peptide', 'longevity', 'Synthetic peptide studied for telomerase activation and longevity.', 'May activate telomerase, the enzyme that maintains telomere length. Studied primarily in animal models for anti-aging effects.', ARRAY['Longevity research','Telomere support','Anti-aging'], ARRAY['May activate telomerase','Studied in longevity research','Well-tolerated in studies'], ARRAY['Primarily animal data','Not FDA-approved','Long-term effects unknown'], ARRAY['Subcutaneous injection'], 'D', true, 'Not FDA-approved'),
('ghk-cu', 'GHK-Cu', 'peptide', 'hair', 'Copper peptide studied for skin, hair, and wound healing.', 'Naturally occurring peptide that binds copper. May promote collagen synthesis, wound healing, and hair follicle support.', ARRAY['Skin health','Hair support','Wound healing','Anti-aging'], ARRAY['May promote collagen synthesis','May support hair growth','May accelerate wound healing'], ARRAY['Skin irritation (topical)','Limited systemic data','Not FDA-approved for these uses'], ARRAY['Topical','Subcutaneous injection'], 'C', false, 'Cosmetic use (topical)'),
('thymosin-alpha-1', 'Thymosin Alpha-1', 'peptide', 'immune', 'Immune-modulating peptide approved in some countries for viral hepatitis.', 'Enhances T-cell function and immune surveillance. Approved in over 35 countries for hepatitis B treatment.', ARRAY['Immune support','Viral conditions','Immune optimization'], ARRAY['May enhance immune function','Approved in multiple countries','Well-studied safety profile'], ARRAY['Injection site reactions','Fatigue','Not FDA-approved in US'], ARRAY['Subcutaneous injection'], 'B', true, 'Approved internationally, not US FDA'),

-- METABOLIC MEDICATIONS
('semaglutide', 'Semaglutide', 'medication', 'metabolic', 'GLP-1 receptor agonist FDA-approved for type 2 diabetes and weight management.', 'Mimics the GLP-1 hormone, reducing appetite, slowing gastric emptying, and improving insulin sensitivity.', ARRAY['Weight management','Type 2 diabetes','Cardiovascular risk reduction'], ARRAY['Significant weight loss in trials','Improved glycemic control','Cardiovascular benefit shown'], ARRAY['Nausea','GI side effects','Pancreatitis risk','Thyroid concerns (animal data)','Gallbladder issues'], ARRAY['Subcutaneous injection','Oral'], 'A', true, 'FDA-approved (Ozempic, Wegovy, Rybelsus)'),
('tirzepatide', 'Tirzepatide', 'medication', 'metabolic', 'Dual GLP-1/GIP receptor agonist FDA-approved for diabetes and weight management.', 'Activates both GLP-1 and GIP receptors, providing enhanced metabolic effects compared to GLP-1 alone.', ARRAY['Weight management','Type 2 diabetes','Metabolic optimization'], ARRAY['Greater weight loss than semaglutide in trials','Improved A1C','Dual mechanism'], ARRAY['Nausea','GI side effects','Pancreatitis risk','Injection site reactions'], ARRAY['Subcutaneous injection'], 'A', true, 'FDA-approved (Mounjaro, Zepbound)'),
('retatrutide', 'Retatrutide', 'medication', 'metabolic', 'Triple agonist (GLP-1/GIP/glucagon) in clinical development for obesity.', 'Activates three metabolic receptors simultaneously. Phase 3 trials showing potentially superior weight loss results.', ARRAY['Weight management','Metabolic research','Obesity treatment'], ARRAY['Potentially superior weight loss','Triple mechanism','Active clinical development'], ARRAY['Still in clinical trials','Not yet approved','GI side effects expected','Long-term safety unknown'], ARRAY['Subcutaneous injection'], 'C', true, 'Investigational — not approved'),

-- HORMONES / HRT
('testosterone-cypionate', 'Testosterone Cypionate', 'hormone', 'hormone_optimization', 'FDA-approved testosterone replacement for diagnosed hypogonadism.', 'Provides exogenous testosterone to restore levels in men with clinically low testosterone, supporting energy, mood, body composition, and sexual function.', ARRAY['Testosterone replacement','Hypogonadism','Body composition','Energy'], ARRAY['Restores testosterone to physiologic levels','May improve energy and mood','May improve body composition','FDA-approved'], ARRAY['Polycythemia','Acne','Sleep apnea worsening','Testicular atrophy','Fertility suppression','Cardiovascular monitoring needed'], ARRAY['Intramuscular injection','Subcutaneous injection'], 'A', true, 'FDA-approved'),
('hcg', 'hCG (Human Chorionic Gonadotropin)', 'hormone', 'hormone_optimization', 'Hormone used alongside TRT to maintain testicular function and fertility.', 'Mimics LH, stimulating the testes to produce testosterone and maintain sperm production during TRT.', ARRAY['Fertility preservation during TRT','Testicular function','Hormone optimization'], ARRAY['Maintains testicular size','Preserves fertility potential','Supports intratesticular testosterone'], ARRAY['Gynecomastia','Mood changes','Limited supply issues','Regulatory changes'], ARRAY['Subcutaneous injection','Intramuscular injection'], 'B', true, 'FDA-approved (fertility)'),
('enclomiphene', 'Enclomiphene', 'hormone', 'hormone_optimization', 'Selective estrogen receptor modulator studied for raising testosterone while preserving fertility.', 'Blocks estrogen receptors in the hypothalamus, increasing LH and FSH production, which stimulates natural testosterone production.', ARRAY['Testosterone optimization','Fertility preservation','Alternative to TRT'], ARRAY['May raise testosterone naturally','Preserves fertility','Oral administration'], ARRAY['Headache','Hot flashes','Visual changes','Not FDA-approved as standalone'], ARRAY['Oral'], 'B', true, 'Not FDA-approved (investigational)'),
('dhea', 'DHEA', 'hormone', 'hormone_optimization', 'Adrenal hormone precursor available as a supplement.', 'Precursor to both testosterone and estrogen. Levels naturally decline with age. Supplementation may support hormone balance.', ARRAY['Hormone precursor','Adrenal support','Anti-aging'], ARRAY['May support hormone levels','Widely available','Well-studied'], ARRAY['Acne','Hair changes','Hormone-sensitive condition risk','May affect other hormones'], ARRAY['Oral','Topical'], 'B', false, 'OTC supplement'),
('pregnenolone', 'Pregnenolone', 'hormone', 'cognitive', 'Master hormone precursor studied for cognitive and mood support.', 'Precursor to virtually all steroid hormones. May support memory, mood, and neurological function.', ARRAY['Cognitive support','Hormone precursor','Mood support'], ARRAY['May support memory','Precursor to multiple hormones','Generally well-tolerated'], ARRAY['May affect downstream hormones','Drowsiness','Irritability'], ARRAY['Oral'], 'C', false, 'OTC supplement'),
('progesterone', 'Progesterone', 'hormone', 'hormone_optimization', 'Hormone used in female and male HRT protocols.', 'Essential hormone for menstrual regulation, pregnancy, and neuroprotection. Used in both female HRT and sometimes male TRT protocols.', ARRAY['Female HRT','Neuroprotection','Sleep support','Male TRT adjunct'], ARRAY['May improve sleep quality','Neuroprotective properties','Essential for female hormone balance'], ARRAY['Drowsiness','Mood changes','Contraindicated in some conditions'], ARRAY['Oral','Topical','Vaginal'], 'A', true, 'FDA-approved'),
('np-thyroid', 'NP Thyroid / Armour Thyroid', 'hormone', 'hormone_optimization', 'Natural desiccated thyroid containing T4 and T3.', 'Derived from porcine thyroid glands. Contains both T4 and T3 hormones, unlike synthetic T4-only medications.', ARRAY['Hypothyroidism','Thyroid optimization','T3+T4 therapy'], ARRAY['Contains both T4 and T3','Some patients prefer over synthetic','Long clinical history'], ARRAY['Dose variability between batches','Overmedication risk','Requires monitoring'], ARRAY['Oral'], 'B', true, 'FDA-approved'),
('levothyroxine', 'Levothyroxine', 'hormone', 'hormone_optimization', 'Synthetic T4 thyroid hormone — most prescribed thyroid medication.', 'Synthetic version of the T4 hormone produced by the thyroid. The body converts T4 to active T3 as needed.', ARRAY['Hypothyroidism','Thyroid replacement'], ARRAY['Well-studied','Consistent dosing','First-line treatment'], ARRAY['Overmedication risk','Requires regular monitoring','Some patients need T3 addition'], ARRAY['Oral'], 'A', true, 'FDA-approved'),
('liothyronine', 'Liothyronine (T3)', 'hormone', 'hormone_optimization', 'Synthetic T3 thyroid hormone for cases needing direct T3 supplementation.', 'Active thyroid hormone. Used when patients do not adequately convert T4 to T3, or as part of combination therapy.', ARRAY['T3 supplementation','Thyroid optimization','Combination therapy'], ARRAY['Direct T3 supplementation','May help poor T4-to-T3 converters','Rapid onset'], ARRAY['Short half-life','Cardiac concerns at high doses','Requires careful dosing'], ARRAY['Oral'], 'B', true, 'FDA-approved'),

-- LONGEVITY / WELLNESS
('nmn', 'NMN (Nicotinamide Mononucleotide)', 'supplement', 'longevity', 'NAD+ precursor studied for cellular energy and longevity.', 'Converted to NAD+ in the body, supporting cellular energy production, DNA repair, and sirtuin activation.', ARRAY['NAD+ support','Cellular energy','Longevity research'], ARRAY['May boost NAD+ levels','May support cellular repair','Active research area'], ARRAY['Limited long-term human data','GI discomfort','Regulatory status varies'], ARRAY['Oral','Sublingual'], 'C', false, 'Supplement (regulatory status varies)'),
('nr', 'NR (Nicotinamide Riboside)', 'supplement', 'longevity', 'NAD+ precursor with human clinical trial data.', 'Another pathway to increase NAD+ levels. Has more published human trial data than NMN.', ARRAY['NAD+ support','Cellular energy','Aging research'], ARRAY['Raises NAD+ in human trials','Generally well-tolerated','Growing evidence base'], ARRAY['GI discomfort','Long-term effects unknown','Expensive'], ARRAY['Oral'], 'B', false, 'Supplement (Tru Niagen)'),
('resveratrol', 'Resveratrol', 'supplement', 'longevity', 'Polyphenol studied for sirtuin activation and cardiovascular health.', 'Found in red wine and grapes. Activates sirtuins and has antioxidant properties. Human evidence is mixed.', ARRAY['Cardiovascular support','Antioxidant','Longevity research'], ARRAY['Antioxidant properties','Sirtuin activation in vitro','Cardiovascular research'], ARRAY['Poor bioavailability','Mixed human trial results','GI discomfort'], ARRAY['Oral'], 'C', false, 'Supplement'),
('rapamycin', 'Rapamycin (Sirolimus)', 'medication', 'longevity', 'mTOR inhibitor FDA-approved as immunosuppressant, studied for longevity.', 'Inhibits mTOR pathway, a key regulator of cell growth and aging. FDA-approved for organ transplant; longevity use is off-label.', ARRAY['Longevity research','mTOR inhibition','Immune modulation'], ARRAY['Extends lifespan in animal models','mTOR inhibition may slow aging','Active human longevity trials'], ARRAY['Immunosuppression','Metabolic effects','Mouth sores','Requires careful monitoring'], ARRAY['Oral'], 'C', true, 'FDA-approved (transplant), off-label longevity'),
('metformin', 'Metformin', 'medication', 'longevity', 'First-line diabetes medication studied for longevity and cancer prevention.', 'Activates AMPK, reduces hepatic glucose production. Large observational data suggests potential longevity benefits.', ARRAY['Blood sugar management','Longevity research','Metabolic health'], ARRAY['Well-studied safety profile','TAME trial ongoing','May reduce cancer risk'], ARRAY['GI side effects','B12 depletion','Lactic acidosis (rare)','May blunt exercise adaptation'], ARRAY['Oral'], 'B', true, 'FDA-approved (diabetes)'),
('glutathione', 'Glutathione', 'supplement', 'immune', 'Master antioxidant studied for detoxification and immune support.', 'The body''s most abundant antioxidant. Supports detoxification, immune function, and cellular protection from oxidative stress.', ARRAY['Detoxification','Immune support','Antioxidant','Skin health'], ARRAY['Powerful antioxidant','Supports liver function','May improve skin brightness'], ARRAY['Oral bioavailability concerns','IV form more effective but requires clinic','GI discomfort'], ARRAY['IV','Oral','Liposomal','Nebulized'], 'B', false, 'Supplement / clinical IV'),
('nad-iv', 'NAD+ (IV Therapy)', 'supplement', 'longevity', 'Direct NAD+ infusion for rapid cellular replenishment.', 'Delivers NAD+ directly into the bloodstream, bypassing oral absorption limitations. Used in clinical longevity and addiction recovery settings.', ARRAY['Cellular energy','Longevity','Addiction recovery','Cognitive support'], ARRAY['Rapid NAD+ elevation','Bypasses absorption issues','Clinical setting safety'], ARRAY['Expensive','Requires IV administration','Flushing and discomfort during infusion','Time-intensive'], ARRAY['IV'], 'C', false, 'Clinical service');

-- PROTOCOL TEMPLATES
INSERT INTO therapy_protocols (slug, name, category, goal, consumer_description, clinical_description, typical_duration, ideal_candidate, expected_outcomes, lifestyle_requirements, lab_markers_to_consider, evidence_rating) VALUES
('recovery-tissue', 'Recovery & Tissue Support', 'recovery', 'Accelerate recovery from injury or chronic tissue stress', 'A comprehensive approach to tissue healing combining targeted peptides with foundational nutrition and movement practices.', 'Multi-modal tissue repair protocol combining BPC-157 and TB-500 with anti-inflammatory support. Best used post-injury or for chronic tendinopathy with provider oversight.', '4-8 weeks', 'Individuals recovering from soft tissue injuries, chronic joint issues, or post-surgical healing.', ARRAY['Improved tissue repair timeline','Reduced inflammation','Better joint mobility','Enhanced recovery between training sessions'], ARRAY['Adequate protein intake (1g/lb)','Sleep optimization (7-9 hours)','Mobility work 3x/week','Avoid re-injury during protocol'], ARRAY['CRP','ESR','CBC'], 'C'),

('metabolic-optimization', 'Metabolic Optimization', 'metabolic', 'Improve body composition and metabolic health', 'A structured approach to metabolic health combining medical therapies with training and nutrition fundamentals.', 'GLP-1/GIP based protocol with strength training, protein optimization, and metabolic marker tracking. Requires ongoing lab monitoring and provider management.', '12-24 weeks', 'Individuals with BMI >27 or metabolic dysfunction who have not responded adequately to lifestyle alone.', ARRAY['Significant body composition improvement','Improved insulin sensitivity','Better cardiovascular markers','Sustainable weight management'], ARRAY['Strength training 3-4x/week','Protein target 1g/lb lean mass','Regular meal timing','Hydration optimization'], ARRAY['Fasting insulin','A1C','Lipid panel','Liver function','Thyroid panel'], 'A'),

('trt-optimization', 'TRT Optimization', 'hormone_optimization', 'Optimize testosterone levels with comprehensive monitoring', 'A carefully managed testosterone replacement protocol with fertility preservation and health monitoring.', 'Standard TRT protocol with hCG for gonadal maintenance, estradiol management, and comprehensive metabolic monitoring. Requires quarterly labs minimum.', 'Ongoing with quarterly review', 'Men with clinically diagnosed hypogonadism confirmed by labs and symptoms.', ARRAY['Improved energy and mood','Better body composition','Enhanced recovery','Improved sexual function'], ARRAY['Resistance training 3-4x/week','Adequate sleep','Cardiovascular exercise','Moderate alcohol'], ARRAY['Total testosterone','Free testosterone','Estradiol','CBC/hematocrit','PSA','Lipids','Liver function','SHBG'], 'A'),

('longevity-foundation', 'Longevity Foundation', 'longevity', 'Build a science-backed foundation for healthy aging', 'Core longevity practices combining cellular support supplements with essential training, sleep, and nutrition habits.', 'Evidence-based longevity stack focusing on NAD+ pathway support, mTOR modulation awareness, and metabolic optimization. Emphasizes lifestyle factors over supplements.', 'Ongoing', 'Health-conscious individuals interested in evidence-based longevity optimization.', ARRAY['Improved cellular energy','Better metabolic markers','Enhanced recovery','Foundation for long-term health'], ARRAY['Resistance training 3x/week','Zone 2 cardio 150min/week','Sleep 7-9 hours','Whole-food nutrition','Stress management'], ARRAY['NAD+ levels (if available)','Inflammation markers (hs-CRP)','Metabolic panel','Vitamin D','Omega-3 index'], 'C'),

('hair-restoration', 'Hair Restoration', 'hair', 'Support hair health and reduce hair loss', 'A multi-approach protocol combining topical treatments, peptides, and lifestyle factors for hair health support.', 'Comprehensive hair protocol addressing DHT, scalp health, and growth factors. Requires provider evaluation of underlying causes before starting.', '6-12 months minimum', 'Individuals experiencing pattern hair loss or thinning who have been evaluated for underlying causes.', ARRAY['Reduced shedding','Improved hair density','Better scalp health','Support for existing follicles'], ARRAY['Consistent daily application','Scalp care routine','Adequate nutrition','Stress management'], ARRAY['DHT levels','Thyroid panel','Iron/ferritin','Vitamin D','Hormone panel'], 'B'),

('inflammation-support', 'Inflammation Support', 'inflammation', 'Reduce chronic inflammation and support immune balance', 'A targeted approach to managing chronic inflammation through peptides, nutrition, and lifestyle modification.', 'Anti-inflammatory protocol combining KPV with omega-3 optimization, gut health support, and inflammatory marker tracking. Addresses root causes alongside symptom management.', '8-16 weeks', 'Individuals with elevated inflammatory markers or chronic inflammatory conditions under provider care.', ARRAY['Reduced inflammatory markers','Improved gut health','Better energy and recovery','Enhanced immune balance'], ARRAY['Anti-inflammatory nutrition','Omega-3 supplementation','Sleep optimization','Stress reduction practices','Gut health support'], ARRAY['hs-CRP','ESR','IL-6','Omega-3 index','Gut health markers','Food sensitivity testing'], 'C');

-- PROTOCOL COMPONENTS
-- Recovery & Tissue Support
INSERT INTO protocol_components (protocol_id, component_name, role_in_protocol, timing_notes, optional, display_order)
SELECT p.id, c.name, c.role, c.timing, c.opt, c.ord
FROM therapy_protocols p,
(VALUES
  ('BPC-157', 'Primary tissue repair peptide', 'Twice daily, typically AM and PM', false, 1),
  ('TB-500', 'Tissue repair and flexibility support', 'Twice weekly loading, then weekly', false, 2),
  ('KPV', 'Anti-inflammatory support', 'Daily during active inflammation', true, 3),
  ('Protein optimization', 'Foundational nutrition', '1g per pound bodyweight daily', false, 4),
  ('Sleep optimization', 'Recovery foundation', '7-9 hours nightly', false, 5),
  ('Mobility work', 'Movement support', '3x/week minimum', false, 6)
) AS c(name, role, timing, opt, ord)
WHERE p.slug = 'recovery-tissue';

-- CONDITIONS
INSERT INTO therapy_conditions (slug, name, description, category) VALUES
('tissue-repair', 'Tissue Repair & Recovery', 'Support for healing tendons, ligaments, muscles, and other soft tissues.', 'recovery'),
('weight-management', 'Weight Management', 'Support for healthy body composition and metabolic function.', 'metabolic'),
('hormone-balance', 'Hormone Balance', 'Optimization of hormonal health through evidence-based approaches.', 'hormone_optimization'),
('longevity', 'Longevity & Aging', 'Support for healthy aging and cellular function.', 'longevity'),
('inflammation', 'Chronic Inflammation', 'Management of inflammatory conditions and immune balance.', 'inflammation'),
('hair-health', 'Hair Health', 'Support for hair growth, density, and scalp health.', 'hair'),
('cognitive-function', 'Cognitive Function', 'Support for memory, focus, and brain health.', 'cognitive'),
('sleep-quality', 'Sleep Quality', 'Optimization of sleep duration and quality.', 'sleep'),
('immune-health', 'Immune Health', 'Support for immune system function and resilience.', 'immune'),
('sexual-health', 'Sexual Health', 'Support for sexual function and reproductive health.', 'sexual_health'),
('gut-health', 'Gut Health', 'Support for digestive function and gut barrier integrity.', 'inflammation'),
('cardiovascular', 'Cardiovascular Health', 'Support for heart and vascular health.', 'metabolic');
