-- ═══════════════════════════════════════════════════════════════
--  Clinical System Tables
--  Supports: care relationships, invite codes, daily check-ins,
--  protocols, and prescriptions.
-- ═══════════════════════════════════════════════════════════════

-- Care invite codes — generated by consumers, accepted by clinicians
CREATE TABLE IF NOT EXISTS care_invite_codes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  code TEXT NOT NULL UNIQUE,
  message TEXT,
  access_level TEXT DEFAULT 'full',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'expired', 'revoked')),
  accepted_by UUID REFERENCES auth.users(id),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE care_invite_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users see own invites" ON care_invite_codes
  FOR ALL USING (auth.uid() = user_id OR auth.uid() = accepted_by);

-- Care relationships — links consumer to clinician
CREATE TABLE IF NOT EXISTS care_relationships (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  patient_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  clinician_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  clinic_name TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'revoked')),
  linked_at TIMESTAMPTZ DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  UNIQUE(patient_id, clinician_id)
);

ALTER TABLE care_relationships ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Participants see relationship" ON care_relationships
  FOR ALL USING (auth.uid() = patient_id OR auth.uid() = clinician_id);

-- Patient check-ins — daily adherence data from iOS app
CREATE TABLE IF NOT EXISTS patient_checkins (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  doses INT DEFAULT 0,
  daily_checkin INT DEFAULT 0,
  workout INT DEFAULT 0,
  nutrition INT DEFAULT 0,
  weight DOUBLE PRECISION,
  sleep_score INT,
  hrv INT,
  rhr INT,
  mood INT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, date)
);

ALTER TABLE patient_checkins ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users see own checkins" ON patient_checkins
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own checkins" ON patient_checkins
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own checkins" ON patient_checkins
  FOR UPDATE USING (auth.uid() = user_id);
-- Clinicians with active relationship can read patient checkins
CREATE POLICY "Clinicians read patient checkins" ON patient_checkins
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM care_relationships
      WHERE care_relationships.patient_id = patient_checkins.user_id
        AND care_relationships.clinician_id = auth.uid()
        AND care_relationships.status = 'active'
    )
  );

-- Patient protocols — assigned by clinician or self-managed
CREATE TABLE IF NOT EXISTS patient_protocols (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phase TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed')),
  assigned_by UUID REFERENCES auth.users(id),
  started_at TIMESTAMPTZ DEFAULT now(),
  ended_at TIMESTAMPTZ,
  config JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE patient_protocols ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users see own protocols" ON patient_protocols
  FOR ALL USING (auth.uid() = user_id OR auth.uid() = assigned_by);

-- Patient prescriptions — medications/supplements within a protocol
CREATE TABLE IF NOT EXISTS patient_prescriptions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  protocol_id UUID NOT NULL REFERENCES patient_protocols(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  drug TEXT NOT NULL,
  dose TEXT NOT NULL,
  frequency TEXT NOT NULL,
  timing TEXT,
  method TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'discontinued')),
  last_filled_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE patient_prescriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users see own prescriptions" ON patient_prescriptions
  FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Clinicians see patient prescriptions" ON patient_prescriptions
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM care_relationships
      WHERE care_relationships.patient_id = patient_prescriptions.user_id
        AND care_relationships.clinician_id = auth.uid()
        AND care_relationships.status = 'active'
    )
  );

-- Indexes
CREATE INDEX IF NOT EXISTS idx_checkins_user_date ON patient_checkins(user_id, date);
CREATE INDEX IF NOT EXISTS idx_care_rel_patient ON care_relationships(patient_id);
CREATE INDEX IF NOT EXISTS idx_care_rel_clinician ON care_relationships(clinician_id);
CREATE INDEX IF NOT EXISTS idx_invite_code ON care_invite_codes(code);
CREATE INDEX IF NOT EXISTS idx_protocols_user ON patient_protocols(user_id);
